---
image: "alpine:latest"
.only-default: &only-default
  only:
    - master
    - wip
    - merge_requests

mr-settings:
  only:
    - merge_requests
  before_script:
    - apk -q add python3
  script:
    - wget -q "https://gitlab.com/postmarketOS/ci-common/-/raw/master/check_mr_settings.py"
    - python3 ./check_mr_settings.py

flake8:
  <<: *only-default
  before_script:
  - "apk -q add py3-pip"
  - "pip3 -q --disable-pip-version-check install flake8"
  script:
  - ".ci/flake8.sh"

vermin:
  <<: *only-default
  before_script:
  - "apk -q add py3-pip"
  - "pip3 -q --disable-pip-version-check install vermin"
  script:
  - ".ci/vermin.sh"

# Run pytest testsuite with debian stretch (python 3.5), which matches the
# production environment. Redirect apt-get stdout to /dev/null, because -qq
# isn't quiet enough (https://askubuntu.com/a/258226).
pytest:
  <<: *only-default
  image: "debian:stretch"
  before_script:
  - ".ci/setup_pytest.sh"
  script:
  - "su pmos -c '.ci/pytest.sh'"
  artifacts:
    when: "on_failure"
    paths:
    - "_html_out/index.html"
    - "_temp/local_job/current_task.sh"
    - "_temp/local_job_logs/*.txt"
    - "pytest.log"
    expire_in: "1 week"
